---
driver:
  name: vagrant
  customize:
    memory: 256
  synced_folders:
    - ["files", "/files", "create: true"]
  provider: vmware_fusion

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[logstash-forwarder-package::default]
    attributes:
